
import LocalizedStrings from 'react-native-localization';

let strings = new LocalizedStrings({


  en:{
Login	:"Login",
accountdetails : "Account Details Updated Successfully",
Signup	:"Signup",
HireFreelancer	:"Hire Freelancer",
Message	:"Message",
WorkHistory	:"Work History",
Feedback	:"Feedback",
NorecordFound : "No Record Found",
Summary	:"Summary",
GoToMilestones  : "Go To Milestones",
MyJobs	:"My Jobs",
Proposal	:"Proposal",
Workinprogress	: "Work in progress",
Budget 	: "Budget",
StartDate	:"Start Date",
EndDate	:"End Date",
Thanks	:"Thanks",
GoBack : "Go Back",
Settings	:"Settings",
Messages	:"Messages",
EnterFeedback:"Enter Your Feedback.....",
Jobs	:"Jobs",
and	:"and",
Invitations	:"Invitations",
Notifications	:"Notifications",
Language :"Language   ",
Startdate : "Start Date",
Skill	:"Skill",
MyAccount	:"My Account",
Freelancer : "(Freelancer)",
Client : "(Client)",
SubmitProposal	:"Submit Proposal",
SelectAccount:"Select Account",
Selectaccounttype	:"Select account type",
Iwanttohirefreelancer	:"I want to hire freelancer",
Iwanttoworkwith	:"I want to work with",
CreateAnAccount:"Create An Account",
Alreadyhaveanaccount	:"Already have an account",
AboutTest1 : "Every Individual Deserves a Website. We believe every individual should have the power to create their own website or online store. If you can point and click, you can create a professional websiteor online store using our free and intuitive tools",
AboutTest2 : " Our Customers Mean the World At Website.com, we strive to provide exactly what our customers are looking for. A huge part of our brainstorming process is looking at our client feedback to makesure you're well taken care of.",
AboutTest3 : " We are personally committed to delivering the very best",
Hire	:"Hire",
AboutTest3 : "", 
clickhere : "Click Here",
MakePayment	:"Make Payment",
CreateMilestones	:"Create Milestones",
Homepage	:"Homepage",
Categories	:"Categories",
Websites	:"Websites",
dueDate : "Due Date",
CreateProject	:"CREATE PROJECT",
updatedsuccessfully : "Updated Successfully",
Submittedsuccessfully : "Submitted Successfully",
Verificationcode:"VERIFICATION CODE",
Resentotp:"Resend OTP",
Changeno:"Change Number",
Enterotp:"Enter the four digit code sent to you at",
SelectJob : "Select Job",

//keshav
Logout:"Log Out",
Signin:"SIGN IN",
Submit:"SUBMIT",
Mobilenumber:"Mobile Number",
Enddate : "End Date",
Gotoprofile:"Go To Profile",
About:"About",
MyBalance:"My Balance",
Jobs:"JOBS",
FindFreelancer:"FIND FREELANCER",
FindWorks:"Find Work",
MyPayment:"My Payments",
MyProject:"My Projects",
Addbankdetail : "Add Bank Detail", 
Payment:"Payments",
Title:"Title",
Country:"Country",
Budget:"Budget",
Date:"Date",
Status:"Status",
Description:"Description",
Jobdetail:"Job Detail",
AccountNumber : "Account Number",
IBAN : "IBAN",
Profile:"Profile",
Username:"User Name",
Emailaddress:"Email Address",
AboutMe	:"About Me",
Usertype:"User Type",
Category:"Category",
Skills:"Skills",
Cv:"CV",
IdProf:"Identity Proof",
Done:"Done",
City:"City",
ClientName : "Client Name",
Startenddate:"Start & End Date",
Completed : "Completed",
Freelancerdetail:"Freelancer Details",
FindFreelancer2 : "Find Freelancer", 
Email:"Email",
Name:"Name",
OpenApp : "Open App",
Shortbio:"Short Bio",
BankCode : "Bank Code",
AddJob:"Add Job",
Subcategory:"Sub Category",
Milestonelist:"Milestone List",
Projectlist:"Project List",
Amount:"Amount",
Freelancername:"Freelancer Name",
FEEDstring : "FEED",
FAVOURITEstring : "FAVOURITE",
Freelancerstring : "Freelancer",
NoRequestFound : "No Request Found",
Searchstring:"Search",
FixedPrice : "Fixed Price",
Accept : "Accept",
Reject : "Reject",
Created : "Created", 
CreateProject : "Create Project",
Hirefreelancer : "Hire freelancer",
EnterMobileNumber : "Enter Mobile Number",
EnterValidMobileNumber : "Enter Valid Mobile Number",
OTPSentSuccessfully : "OTP Sent Successfully",
NetworkError : "Network Error",
clicktoview: "Click To View",
GoToProjects : "Go To Project",
SelectCitystring : "Select City",
Ratereview : "Rate & Review",
SelectCategorystring : "Select Category",
Enteramount : "Enter amount",
StatusUpdatedSuccessfully : "Status Updated Successfully",
Requestaccpetsuccessfully	:"Request Accepted Successfully",
RequestReject	:"Request Rejected",
Enterskills : "Enter skills",
SubmitSuccessfully	:"Submit Successfully",
PleaseEnterFeedback	:"Please Enter Feedback",
Fillallrequireddetails : "Fill all required details",
JobAddedSuccessfully : "Job added successfully",
AnErrorOccured : "An Error Occured",
RequestSendSuccessfully : "Request sent successfully",
AlreadySentRequest : "Already sent request",
HiredSuccessfully : "Hired Successfully",
DueDate : "Due Date",
PleaseEnterAmount : "Please Enter Amount",
PleaseentervalidDueDate : "Please enter valid Due Date",
PleaseenterDescription : "Please enter Description",
MilestoneCreatedSuccessfully : "Milestone Created Successfully",
ProfileUpdatedSuccessfully : "Profile Updated Successfully",
Pleasefillalldetails : "Please fill all details",
Pleaseselectvalidfileformat : "Please select valid file format",
Pleaseentervalidemail : "Please enter valid email",
Addskills : "Add skills",
bankdetail : "Bank Detail",
JobAddedtoFavouritesSuccessfully : "Job added to favourites successfully",
ProjectCreatedSuccessfully : "Project Created Successfully",
JobRemovedFromFavoritesSuccessfully : "Job Removed From Favourites Successfully",
NomessagesFound: "No Messages Found",
Invalidenddate : "Invalid end date",
ExitApp:"Exit App",
DoyouwanttoExittheapplication: "Do you want to Exit the application?",
Cancel : "CANCEL",
cancel : "CANCEL",
NoMilestonefound : "No Milestone Found! Create New",
Submit : "SUBMIT",
Writeareview : "Write a review.....",
ChatwithFreelancer : "Chat With Freelancer",
NochatFound: "No Chat Found",
NoSubCategoryFound : "No SubCategory Found",
ok : "Ok",
ViewClientProfile : "View Client's Profile",
typeamessage : "Type a message...",
Entermessage : "Enter message",
Alertstring : "Alert!",
NoJobFound: "No Job Found",
Chatwithclient : "Chat With Client",
NoFreelancerFound : "No Freelancer Found",
CV : "C.V",
Finish : "Finish", 
Finished : "Finished", 
Pay : "Pay",
Paid : "Paid", 
IDProof : "I.D Proof",
seeJobRequests : "See job requests",
NoNotificationRecieved  : "No Notification Received",
Requests : "Requests",
NoProjectFound : "No Project Found ! Create New",
ViewMilestones : "View Milestones",
milestoneAmountError :"Milestone Amount Exceeds Project Amount",
GiveRating : "Give Rating",
MakePayment : "Make Payment",
CreateMilestones : "Create Milestones"
  },



  
hn:
{
  Login : "लॉग इन करें",
  seeJobRequests : "انظر طلبات العمل",

  Alertstring : "محزر!",
  Entermessage : "أدخل رسالة",
  typeamessage : "اكتب رسالة ...",
  cancel : "إلغاء",
  DoyouwanttoExittheapplication: "هل تريد الخروج من التطبيق؟",
  ExitApp : "الخروج من التطبيق",
  ProjectCreatedSuccessfully : "تم إنشاء المشروع بنجاح",
  JobAddedtoFavouritesSuccessfully : "الوظيفة المضافة إلى المفضلة بنجاح",
  Addskills : "إضافة المهارات",
  MilestoneCreatedSuccessfully : "معلم خلقت بنجاح",
  PleaseenterDescription : "يرجى إدخال الوصف",
  PleaseentervalidDueDate : "الرجاء إدخال تاريخ الاستحقاق الساري",
  PleaseEnterAmount : "يرجى إدخال المبلغ",
  DueDate : "تاريخ الاستحقاق",
  HiredSuccessfully : "استأجر بنجاح",
  AlreadySentRequest : "تم إرسال الدعوة مسبقا",
  RequestSendSuccessfully : "تم إرسال الطلب بنجاح",
  AnErrorOccured : "حدث خطأ",
  JobAddedSuccessfully : "الوظيفة المضافة بنجاح",
  Fillallrequireddetails : "املأ جميع التفاصيل المطلوبة",
  SubmitSuccessfully	:"يقدم بنجاح",
  PleaseEnterFeedback	:"يرجى إدخال ملاحظات",
  Enterskills : "أدخل المهارات",
  Requestaccpetsuccessfully	:"تم قبول الطلب بنجاح",
  RequestReject	:"طلب رفض",
  Enteramount : "أدخل المبلغ",
  SelectCategorystring : "اختر الفئة",
  SelectCitystring : "اختر مدينة",
  GoToProjects : "اذهب إلى المشروع",
  NetworkError : "خطأ في الشبكة",
  OTPSentSuccessfully : "OTP تم إرساله بنجاح",
  EnterValidMobileNumber : "ادخل رقم هاتف خلوي ساري المفعول",
  EnterMobileNumber : "أدخل رقم الجوال",
  Signup	:"سجل",
  HireFreelancer	:"استئجار لحسابهم الخاص",
  Message	:"رسالة",
  WorkHistory	:"تاريخ العمل",
  Feedback	:"ردود التعليقات المستخدمين",
  Summary	:"ملخص",
  MyJobs	:"وظائفي",
  Proposal	:"اقتراح",
  Workinprogress	:"أعمال جارية",
  Budget 	:"ميزانية",
  StartDate	:"تاريخ البدء",
  EndDate	:"تاريخ الانتهاء",
  Thanks	:"شكر",
  Settings	:"الإعدادات",
  Messages	:"رسائل",
  Jobs	:"وظائف",
  and	:"و",
  Invitations	:"دعوات",
  Notifications	:"إخطارات",
  Language:"لغة   ",
  Skill	:"مهارة",
  MyAccount	:"حسابي",
  ok : "حسنا",
  SubmitProposal	:"تقديم الاقتراح",
  
  SelectAccount:"حدد حساب",
  Selectaccounttype	:"اختر نوع الحساب",
  Iwanttohirefreelancer	:"اريد توظيف المستقل",
  Iwanttoworkwith	:"اريد ان اعمل مع",
  CreateAnAccount:"انشئ حساب",
  Alreadyhaveanaccount	:"هل لديك حساب",
  Hire :"توظيف",
  MakePayment	:"قم بالدفع",
  CreateMilestones	:"إنشاء معالم",
  Homepage	:"الصفحة الرئيسية",
  Categories	:"الاقسام",
  Websites	:"المواقع",

  Verificationcode:"شيفرة التأكيد",
  Resentotp:"استياء اوت",
  Enterotp:"أدخل الرمز المكون من أربعة أرقام الذي تم إرساله إليك على",
  Changeno:"تغيير رقم",

  Logout:"الخروج",
  Submit:"خضع",
  Signin:"تسجيل الدخول",
  Mobilenumber:"رقم الهاتف المحمول",

  Gotoprofile:"اذهب إلى الملف الشخصي",
  About:"عن التطبيق",
  
  MyBalance:"رصيدي",
  Jobs:"وظائف",
  FindFreelancer:"البحث عن مقدم خدمة",
  FindWorks:"البحث عن الأشغال",
  MyPayment:  "المدفوعات الخاصة بي",
  MyProject:"مشاريعي",

  Payment: "المدفوعات",
Title:"عنوان",
Country:"بلد",
Budget:"ميزانية",
Date:"تاريخ",
Status:"الحالة",
Description:"وصف",
Jobdetail:"تفاصيل المهمة",

Profile:"الملف الشخصي",
Username:"اسم المستخدم",
Emailaddress:"عنوان بريد الكتروني",
AboutMe	:"عني",
Usertype:"نوع المستخدم",
Category:"الفئة",
Skills:"مهارات",
Cv:"السيرة الذاتية",
IdProf:"إثبات الهوية",
Done:"فعله",
Startenddate:"تاريخ البدء والانتهاء",
City:"مدينة",


Freelancerdetail:"تفاصيل مستقلة",
Email:"البريد الإلكتروني",
Name:"اسم",
Shortbio:"السيرة الذاتية القصيرة",
AddJob:"اضافة مشروع/ مشاريعي الحالية",
Subcategory:"فرعية",

Milestonelist:"قائمة المعالم",
Projectlist:"قائمة المشروع",
Amount:"كمية",

Freelancername:"اسم حر",
FEEDstring : "تغذية",
FAVOURITEstring : "مفضل",
Freelancerstring : "مستقل",
NoRequestFound : "لم يتم العثور على طلب",
Searchstring:"بحث",
FixedPrice : "سعر ثابت",
Accept : "قبول",
Reject : "رفض",
Hirefreelancer : "استئجار المستقل",
CreateProject	:"خلق المشروع",
ProfileUpdatedSuccessfully : "تم تحديث الملف الشخصي بنجاح",
Pleasefillalldetails : "يرجى ملء جميع التفاصيل",
Pleaseselectvalidfileformat : " يرجى تحديد تنسيق ملف صالح",
Pleaseentervalidemail : "الرجاء إدخال بريد إلكتروني صحيح",
JobRemovedFromFavoritesSuccessfully : "تمت إزالة المهمة من المفضلة بنجاح",
NomessagesFound: "لا توجد رسائل",
NochatFound : "لم يتم العثور على دردشة",
Invalidenddate : "تاريخ غير صالح",
Cancel : "إلغاء",
Submit : "تتفيذ",
Writeareview : "أكتب مراجعة",
ChatwithFreelancer : "الدردشة مع المستقل",
NoSubCategoryFound : "لا يوجد تصنيف فرعي",
NoMilestonefound : "لا يوجد معلم العثور على إنشاء جديد",
NoJobFound : "لا يوجد وظيفة",
NoFreelancerFound : "لم يتم العثور على عمل حر",
AboutTest1 : "كل فرد يستحق موقعًا إلكترونيًا نؤمن بكل فرد يجب أن يكون لديك القدرة على إنشاء موقع الويب الخاص بهم أو متجر على الإنترنت. إذا تمكنت من الإشارة والنقر ، يمكنك إنشاء موقع ويب محترفأو متجر عبر الإنترنت باستخدام أدواتنا المجانية والبديهية.",
AboutTest2 : "عملاؤنا يعني العالم في Website.com ، ونحن نسعى جاهدين لتوفير بالضبط ما يبحث عنه عملاؤنا. جزء كبير من عملية العصف الذهني لدينا يبحث في ملاحظات عملائنا بالتأكيد كنت تعتني جيدا",
AboutTest3 : "نحن ملتزمون شخصيا بتقديم الأفضل",
Chatwithclient : "الدردشة مع العميل",
CV : "السيرة الذاتية",
IDProof : "إثبات الهوية",
ViewClientProfile : "عرض الملف الشخصي للعميل",
NoNotificationRecieved : "لا تلقى إعلام",
NorecordFound : "لا يوجد سجلات",
SelectJob : "اختر الوظيفة",
EnterFeedback:"أدخل ملاحظاتك....",
Requests : "طلبات",
Freelancer : "(مستقل)",
Client : "(عميل)",
Startdate : "تاريخ البدء",
Enddate : "تاريخ الانتهاء",
clicktoview : "اضغط للعرض",
updatedsuccessfully : "تم التحديث بنجاح",
NoProjectFound : "لا يوجد مشروع خلق جديد إبداع جديد",
ViewMilestones : "عرض معالم",
milestoneAmountError : "مبلغ هام يتخطى مبلغ المشروع",
Finished : "تم الانتهاء من", 
Finish : "إنهاء", 
Pay : "دفع",
Paid : "دفع",
Created : "خلقت",
GiveRating : "منح التقييم",
Submittedsuccessfully :  " تم الإرسال بنجاح",
StatusUpdatedSuccessfully : "تم تحديث الحالة بنجاح",
MakePayment : "قم بالدفع",
CreateMilestones : "إنشاء معالم",
CreateProject : "خلق المشروع",
GoToMilestones : "الذهاب إلى معالم",
ClientName : "اسم العميل",
Completed : "منجز",
Ratereview : "مراجعة معدل",
dueDate : "تاريخ الاستحقاق",
Addbankdetail : "إضافة تفاصيل البنك",
clickhere : "انقر هنا",
bankdetail : "تفاصيل البنك",
IBAN : "كانوا",
BankCode : "رمز بنكي",
AccountNumber : "رقم حساب",
FindFreelancer2 : "البحث عن عمل حر",
accountdetails : "تفاصيل الحساب تم تحديثها بنجاح",
OpenApp : "افتح التطبيق",
GoBack : "عد"
}
});
export default strings;
